/*Query to check which transactions are already posted*/

select * from mtl_material_transactions
where transaction_date >=
to_date('01-MAR-2021 00:00:00', 'DD-MON-RRRR HH24:MI:SS')
and transaction_date <=
to_date('31-MAR-2021 23:59:59', 'DD-MON-RRRR HH24:MI:SS')
and opm_costed_flag IS NULL
and organization_id IN (SELECT organization_id
FROM gmf_organization_definitions
WHERE legal_entity_id = 23273);


/*Query to check which total number of transactions are already posted*/

select god.legal_entity_id, to_char(mmt.transaction_date, 'YYYY-MM'),
mmt.opm_costed_flag, count(mmt.transaction_id)
from mtl_material_transactions mmt, gmf_organization_definitions god
where mmt.transaction_action_id not in (2, 28) and mmt.opm_costed_flag is null
and mmt.organization_id = god.organization_id
AND god.legal_entity_id = 23273
AND to_char(mmt.transaction_date, 'YYYY-MM') ='2021-03'
group by god.legal_entity_id, to_char(mmt.transaction_date, 'YYYY-MM'), mmt.opm_costed_flag;


/*Some findings by Fahim bhai*/

SELECT * FROM GMF_XLA_EXTRACT_HEADERS where TRANSACTION_ID  IN( 9685914) --4911717,4911442,4911409,

select * from xla_ae_headers where event_id=3924166

select * from xla_ae_lines where ae_header_id=33272211

--=============================================================

--==========================================================
-- MTL MATERIAL TRANSACTION TABLE A "SEP-18" ER SOKOL DATA SHOW  KORANOR QUERY
--==========================================================

SELECT  TO_CHAR(A.TRANSACTION_DATE,'MON-YY') PERIOD_CODE,GET_ORG_CODE_FROM_ID(ORGANIZATION_ID) INV_ORG_CODE,B.TRANSACTION_TYPE_NAME,
 A.*  FROM MTL_MATERIAL_TRANSACTIONS A, MTL_TRANSACTION_TYPES B  WHERE INVENTORY_ITEM_ID= 180 
 AND A.TRANSACTION_TYPE_ID = B.TRANSACTION_TYPE_ID
AND TRANSACTION_DATE BETWEEN '01-SEP-2018' AND '30-SEP-2019'    
AND ORGANIZATION_ID= 152   

SELECT * FROM MTL_TRANSACTION_TYPES

-- ==============================================================

-- =============================================================






select * from  RCV_SHIPMENT_HEADERS WHERE RECEIPT_NUM IN  (80000653,80000654,80000655,80000656) and SHIP_TO_ORG_ID= 166  --ORG_ORGANIZATION_DEFINITIONS 

SELECT * FROM RCV_TRANSACTIONS WHERE SHIPMENT_HEADER_ID IN (438129,438130,438131,438132) and TRANSACTION_TYPE = 'DELIVER'

SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE RCV_TRANSACTION_ID IN (317083,317089,317087,317085)

SELECT A.ORGANIZATION_ID,C.RECEIPT_NUM GRN_NO, TO_CHAR(A.transaction_DATE,'DD-MON-RR HH12:MI:SS PM') MMT_transaction_DATE,TO_CHAR(A.transaction_DATE,'DD-MON-RR HH12:MI:SS PM') RCV_transaction_DATE 
FROM RCV_TRANSACTIONS A, MTL_MATERIAL_TRANSACTIONS B, RCV_SHIPMENT_HEADERS C
WHERE A.ORGANIZATION_ID= B.ORGANIZATION_ID 
and A.TRANSACTION_ID = B.RCV_TRANSACTION_ID
AND A.SHIPMENT_HEADER_ID = C.SHIPMENT_HEADER_ID
AND A.TRANSACTION_ID IN (
317083,
317089,
317087,
317085)


--=====================================================

--=====================================================

select GET_ORG_CODE_FROM_ID(A.ORGANIZATION_ID) INV_ORG_CODE, XXGET_ITEM_DESCRIPTION(A.INVENTORY_ITEM_ID,A.ORGANIZATION_ID ) INVENTORY_ITEM_NAME,
TO_CHAR(A.transaction_DATE,'DD-MON-RR') MMT_transaction_DATE, 
TO_CHAR(B.STATUS_DATE,'DD-MON-RR') STATUS_DATE , QUANTITY_DELIVERED 
from mtl_material_transactions A , MTL_TXN_REQUEST_LINES  B 
where A.MOVE_ORDER_LINE_ID = B.LINE_ID
and A.ORGANIZATION_ID= B.ORGANIZATION_ID 
and TRANSACTION_DATE BETWEEN '01-SEP-2018' and '30-SEP-2018'
and  A.INVENTORY_ITEM_ID = 180 
 -- and MOVE_ORDER_LINE_ID = 298555



select * from ORG_ORGANIZATION_DEFINITIONS
--===================================

SELECT * from mtl_material_transactions A , MTL_TXN_REQUEST_LINES  B 
where A.MOVE_ORDER_LINE_ID = B.LINE_ID
and A.ORGANIZATION_ID= B.ORGANIZATION_ID 
and TRANSACTION_DATE BETWEEN '01-SEP-2018' and '30-SEP-2018'
 and  A.INVENTORY_ITEM_ID = 180  
  and MOVE_ORDER_LINE_ID = 298555


select * from MTL_TXN_REQUEST_HEADERS TOH 


select * from   MTL_TXN_REQUEST_LINES TOL where line_id= 298555 





--==========================================
-- RCV TRANS DATE IS NOT SAME AS MMT TRANS DATE QUERY
--=========================================


SELECT B.ORGANIZATION_ID, GET_ORG_CODE_FROM_ID(B.ORGANIZATION_ID) INV_ORG_CODE,B.INVENTORY_ITEM_ID,XXGET_ITEM_DESCRIPTION(B.INVENTORY_ITEM_ID,B.ORGANIZATION_ID ) INVENTORY_ITEM_NAME, A.SHIPMENT_HEADER_ID,A.TRANSACTION_TYPE, A.TRANSACTION_ID,B.RCV_TRANSACTION_ID,  TO_CHAR(A.transaction_DATE,'DD-MON-RR') RCV_transaction_DATE,
TO_CHAR(B.transaction_DATE,'DD-MON-RR') MMT_transaction_DATE, B.PRIMARY_QUANTITY
--TO_CHAR(A.CREATION_DATE,'DD-MON-RR') RCV_CREATION_DATE,
--TO_CHAR(B.CREATION_DATE,'DD-MON-RR') MMT_CREATION_DATE, 
--, A.TRANSACTION_DATE, B.TRANSACTION_DATE 
   FROM RCV_TRANSACTIONS A, mtl_material_transactions B, ORG_ORGANIZATION_DEFINITIONS C 
WHERE A.TRANSACTION_ID = B.RCV_TRANSACTION_ID
AND B.ORGANIZATION_ID = C.ORGANIZATION_ID
--AND B.ORGANIZATION_ID= 166
--and B.INVENTORY_ITEM_ID = 180
--and B.TRANSACTION_DATE <  (TRUNC(A.TRANSACTION_DATE)-25)
and A.TRANSACTION_DATE <> (TRUNC(B.TRANSACTION_DATE)-30) 
AND A.TRANSACTION_DATE BETWEEN '01-OCT-2018' and '31-OCT-2018'
--AND A.TRANSACTION_DATE BETWEEN '01-OCT-2018' and '31-OCT-2018'
--AND A.TRANSACTION_DATE BETWEEN '01-NOV-2018' and '30-NOV-2018'
--AND A.TRANSACTION_DATE BETWEEN '01-DEC-2018' and '30-DEC-2018'
--and A.TRANSACTION_DATE    LIKE '%DEC-19%'  
and C.LEGAL_ENTITY = 26280 
and INVENTORY_ITEM_ID = 180
--and c.operating_unit=81
--and B.TRANSACTION_DATE   NOT  LIKE '%DEC-19%'  
--AND B.RCV_TRANSACTION_ID IN (
--320481,
--320861,
--329284
--)
--and A.SHIPMENT_HEADER_ID = 438222 

-- GET BATCH STATUS WHICH ARE NOT COMPLETED YET
--============================================

SELECT o.ORGANIZATION_CODE, o.ORGANIZATION_NAME, o.ORGANIZATION_ID,
gbh.BATCH_NO,decode(gbh.BATCH_STATUS,-1,'Canceled', 3,'Completed',4,'Closed',2,'WIP',
'Just Created') Batch_Status,to_char(gbh.creation_date,'DD-MON-YYYY HH24:MI:SS AM') creation_date
FROM GME_BATCH_HEADER gbh,
ORG_ORGANIZATION_DEFINITIONS o
WHERE to_char(CREATION_DATE,'MM-YYYY')='06-2021'
AND gbh.ORGANIZATION_ID=o.ORGANIZATION_ID
AND o.ORGANIZATION_ID=173
ORDER BY gbh.creation_date desc


select * from GME_BATCH_HEADER where  BATCH_NO = 2712 and ORGANIZATION_ID=121



--create table mtl_material_trans_temp_jan21 as

select *
 from MTL_MATERIAL_TRANSACTIONS_TEMP
  where to_char (transaction_date,'MON-YYYY')='APR-2021'
  and ORGANIZATION_ID in (121,150,149,148,147,146,145,144,143,142,141)
  
  and transaction_source_id  in (select distinct transaction_source_id from mtl_material_transactions where to_char (transaction_date,'MON-YYYY')='APR-2021')
  
  
  
  

/*Pending Check*/
  select * from   MTL_MATERIAL_TRANSACTIONS_TEMP
  where to_char (transaction_date,'MON-YYYY')='APR-2021'
  and ORGANIZATION_ID in (121,150,149,148,147,146,145,144,143,142,141)
  
  select * from MTL_TRANSACTIONS_INTERFACE
where to_char (transaction_date,'MON-YYYY')='APR-2021'
AND ORGANIZATION_ID in (121,150,149,148,147,146,145,144,143,142,141)
  
--  delete from MTL_MATERIAL_TRANSACTIONS_TEMP
--    where to_char (transaction_date,'MON-YYYY')='MAR-2020'
--  and ORGANIZATION_ID in (121,150,149,148,147,146,145,144,143,142,141)


--================================================
/* OPM BATCH CHECKING WHETHER IT IS WIP, COMPLETE OR CLOSE*/
--================================================

SELECT        GMD.ORGANIZATION_ID, GMD.BATCH_ID, MTT.TRANSACTION_TYPE_ID, MTT.TRANSACTION_TYPE_NAME,
       GBH.BATCH_NO,
       ACTUAL_START_DATE,
       ACTUAL_CMPLT_DATE,
       BATCH_CLOSE_DATE,
       BATCH_STATUS,
       TRANSACTION_DATE,
       GBH.LAST_UPDATE_DATE,
       GMD.CREATED_BY,
       ACTUAL_QTY,
       GMD.INVENTORY_ITEM_ID,
       TRANSACTION_ID,
       MTL.TRANSACTION_TYPE_ID,
       TRANSACTION_QUANTITY
  --,DISTRIBUTION_ACCOUNT_ID
  FROM GME_BATCH_HEADER GBH,
       gme_material_details GMD,
       MTL_MATERIAL_TRANSACTIONS MTL,
       MTL_TRANSACTION_TYPES  MTT
 WHERE     1 = 1
       AND MTL.transaction_SOURCE_ID = GBH.BATCH_ID
       and MTL.TRANSACTION_TYPE_ID= MTT.TRANSACTION_TYPE_ID
       AND MTL.transaction_SOURCE_ID = GMD.BATCH_ID
       AND GBH.BATCH_ID = GMD.BATCH_ID
       AND GMD.INVENTORY_ITEM_ID = MTL.INVENTORY_ITEM_ID
     -- AND GBH.ORGANIZATION_ID = 121
       --AND TO_CHAR (TRANSACTION_DATE, 'MM-YYYY') = '05-2020'   -- 
       and batch_status  IN ( 1,2,3)
      and  ACTUAL_CMPLT_DATE   BETWEEN '10-JUN-2021' and '30-JUN-2021'





--GRN ISSUE

select A.SHIP_TO_ORG_ID, GET_ORG_CODE_FROM_ID(A.SHIP_TO_ORG_ID) INV_ORG_CODE,  A.RECEIPT_NUM, A.SHIPMENT_HEADER_ID,  XX_GET_EMP_NAME_FROM_USER_ID (C.CREATED_BY) CREATED_BY,A.SHIPMENT_NUM, TO_CHAR(C.CREATION_DATE,'DD-MON-RRRR HH12:MI:SS PM') CREATION_DATE,
 C.TRANSACTION_TYPE, 
TO_CHAR(C.TRANSACTION_DATE,'DD-MON-RRRR HH12:MI:SS PM') TRANSACTION_DATE,  C.QUANTITY
from RCV_TRANSACTIONS C, RCV_SHIPMENT_HEADERS A
 --WHERE TRUNC(TRANSACTION_DATE) BETWEEN (TRUNC(CREATION_DATE)-30) AND TRUNC(P_PR_APP_DT)
WHERE C.SHIPMENT_HEADER_ID= A.SHIPMENT_HEADER_ID
and TRANSACTION_DATE <  (TRUNC(C.CREATION_DATE)-30) 
--and organization_ID= 121
and a.CREATION_DATE between '01-JAN-2021' and '30-JUN-2021'
--and C.TRANSACTION_TYPE IN ('DELIVER','TRANSFER','RETURN TO VENDOR')
and A.SHIP_TO_ORG_ID <> 362
--and a.receipt_num = 80000489
 and a.CREATED_BY <>  1462
ORDER BY C.CREATION_DATE DESC


select * from rcv_shipment_headers where receipt_num= 80001208 and ship_to_org_Id=145


select AMOUNT_BILLED, QUANTITY_BILLED from RCV_TRANSACTIONS 
where SHIPMENT_HEADER_ID =1043001 
--and  TRANSACTION_TYPE  IN ('RECEIVE', 'ACCEPT')
--and TRANSACTION_TYPE <>  'DELIVER'


select * from MTL_MATERIAL_TRANSACTIONS WHERE RCV_TRANSACTION_ID IN (965569,
965564,
965568,
965572) 


select * from RCV_TRANSACTIONS 
where SHIPMENT_HEADER_ID =27007 -- 1043001 
--and  TRANSACTION_TYPE  IN ('RECEIVE', 'ACCEPT')
--and TRANSACTION_TYPE <>  'DELIVER'







SELECT  * FROM MTL_MATERIAL_TRANSACTIONS 
WHERE  TRANSACTION_DATE <  (TRUNC(CREATION_DATE)-300) 
and organization_ID= 121
and CREATION_DATE between '01-JAN-2021' and '30-JUN-2021'

--=======================================================
--- TO GET TRANSACTION_DATE IS LESS THAN CREATION DATE  IN GRN SCREEN 
--=======================================================

SELECT GET_ORG_CODE_FROM_ID(A.SHIP_TO_ORG_ID) INV_ORG_CODE, a.RECEIPT_NUM,a.shipment_num, b.transaction_id TRANS_ID,
    TO_CHAR(b.CREATION_DATE,'DD-MON-RRRR HH12:MI:SS PM') CREATION_DATE,
 TO_CHAR(b.transaction_DATE,'DD-MON-RRRR HH12:MI:SS PM') transaction_DATE,
b.TRANSACTION_TYPE,
XXGET_ITEM_DESCRIPTION(c.INVENTORY_ITEM_ID,A.ORGANIZATION_ID) ITEM_DESC,
C.TRANSACTION_DATE MMT_TRANS_DATE,a.SHIPMENT_HEADER_ID, a.LAST_UPDATE_DATE, 
XX_GET_EMP_NAME_FROM_USER_ID (B.CREATED_BY) CREATED_BY
 FROM RCV_SHIPMENT_HEADERS  a, RCV_TRANSACTIONS b, MTL_MATERIAL_TRANSACTIONS c
 where 1=1
 and B.TRANSACTION_DATE < (TRUNC(b.CREATION_DATE)-1) 
 and a.SHIPMENT_HEADER_ID = b.SHIPMENT_HEADER_ID
 and b.TRANSACTION_ID = c.RCV_TRANSACTION_ID
 and b.CREATION_DATE between '01-JAN-2021' and '30-JUN-2021'
 and b.TRANSACTION_TYPE = 'DELIVER'  
 
 select * from mtl_MATERIAL_TRANSACTIONS where RCV_SHIPMENT_NUM='INT-KBA-0032070'
 
 select * from RCV_SHIPMENT_HEADERS
 WHERE RECEIPT_NUM= 80017645
 and ship_to_org_id= 163
 
 select * from rcv_transactions where SHIPMENT_HEADER_ID = 1026074
 
 
 
 
 --========================================= 0 ============================================= 0 =============================================
 --========================================= 0 ============================================= 0 =============================================
 
 

select * from MTL_MATERIAL_TRANSACTIONS where TRANSACTION_SOURCE_ID = 727402

select * from GME_BATCH_HEADER where BATCH_ID= 727402


select GET_ORG_CODE_FROM_ID(A.ORGANIZATION_ID) INV_ORG_CODE ,
GET_ORG_CODE_FROM_ID(B.ORGANIZATION_ID) INV_ORG_CODE,
 a.TRANSACTION_ID,
  TO_CHAR(B.ACTUAL_START_DATE,'DD-MON-RRRR HH12:MI:SS PM') ACTUAL_START_DATE,
  TO_CHAR(B.ACTUAL_CMPLT_DATE,'DD-MON-RRRR HH12:MI:SS PM') ACTUAL_CMPLT_DATE,
  TO_CHAR(A.TRANSACTION_DATE,'DD-MON-RRRR HH12:MI:SS PM') TRANSACTION_DATE,
--A.TRANSACTION_TYPE_ID,
C.TRANSACTION_TYPE_NAME,
-- a.INVENTORY_ITEM_ID,
  XXGET_ITEM_DESCRIPTION(a.INVENTORY_ITEM_ID,A.ORGANIZATION_ID) ITEM_DESC,
 a.PRIMARY_QUANTITY, 
--  B.ACTUAL_CMPLT_DATE,
 --B.ACTUAL_START_DATE,
-- a.TRANSACTION_DATE,
 XX_GET_EMP_NAME_FROM_USER_ID (A.CREATED_BY) CREATED_BY,
B.BATCH_ID, b.BATCH_NO,  B.BATCH_STATUS , XX_GET_EMP_NAME_FROM_USER_ID (B.CREATED_BY) BATCH_CREATED_BY, a.SUBINVENTORY_CODE 
 from MTL_MATERIAL_TRANSACTIONS A, GME_BATCH_HEADER B, MTL_TRANSACTION_TYPES C 
WHERE a.TRANSACTION_SOURCE_ID = B.BATCH_ID 
AND A.TRANSACTION_TYPE_ID = C.TRANSACTION_TYPE_ID
--and b.BATCH_ID= 728982
and a.TRANSACTION_DATE  < (TRUNC(B.ACTUAL_CMPLT_DATE)-30) 
and C.TRANSACTION_TYPE_NAME LIKE '%WIP%' 
--and B.ACTUAL_START_DATE  between '01-JAN-2021' and '30-JUN-2021'
--and A.TRANSACTION_SOURCE_ID = 726239
--and A.ORGANIZATION_ID = 121



SELECT * FROM GME_BATCH_HEADER 
where  BATCH_ID= 726239  -- ACTUAL_START_DATE > ACTUAL_CMPLT_DATE 

SELECT RCV_shipment_num FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_SOURCE_ID=726239


--==================================== MOVE ORDER  QUERY ==================================================

--  GET  MOVE ORDER CREATION IS GREATER THAN TRANSACTION DATE KSPL OU

SELECT GET_ORG_CODE_FROM_ID(TOH.ORGANIZATION_ID) INV_ORG_CODE , TOH.ORGANIZATION_ID, MMT.TRANSACTION_ID TRANSACTION_ID, 
TO_CHAR(TOH.CREATION_DATE,'DD-MON-RRRR HH12:MI:SS PM') CREATION_DATE,
TO_CHAR(mmt.transaction_date,'DD-MON-RRRR HH12:MI:SS PM') transaction_date, 
TOH.HEADER_ID WITH_HEADER_ID,
 XX_GET_EMP_NAME_FROM_USER_ID (TOH.CREATED_BY) CREATED_BY,
  TOL.ORGANIZATION_ID,
  TOH.REQUEST_NUMBER,
  TOH.HEADER_ID,
  TOL.LINE_NUMBER,
  TOL.LINE_ID,
  TOL.INVENTORY_ITEM_ID,
  MY_PACKAGE.XXGET_ITEM_DESCRIPTION(TOL.INVENTORY_ITEM_ID) ITEM_DESCRIPTION,
  TOH.DESCRIPTION,
  TOH.MOVE_ORDER_TYPE,
  TOL.LINE_STATUS,
  TOL.QUANTITY,
  TOL.QUANTITY_DELIVERED,
  TOL.QUANTITY_DETAILED
FROM MTL_TXN_REQUEST_HEADERS TOH,
  MTL_TXN_REQUEST_LINES TOL,
  MTL_MATERIAL_TRANSACTIONS MMT
WHERE TOH.HEADER_ID = TOL.HEADER_ID
 AND TOH.ORGANIZATION_ID= TOL.ORGANIZATION_ID
 AND TOL.LINE_ID = MMT.MOVE_ORDER_LINE_ID(+)
 and  MMT.TRANSACTION_DATE  < (TRUNC(TOH.CREATION_DATE )-2)   
 and TOH.CREATION_DATE between  '01-JAN-2021' and '30-JUN-2021'
 --and MMT.TRANSACTION_ID = 204029
 
 and TOH.ORGANIZATION_ID IN (
 121,
150,
149,
148,
147,
146,
145,
144,
143,
142,
141
 )
--AND TOH.REQUEST_NUMBER='MO-KSM-0099679'
 --and TOH.HEADER_ID IN (1764072)
-- )


--  GET  MOVE ORDER CREATION IS GREATER THAN TRANSACTION DATE KBIL  OU

SELECT GET_ORG_CODE_FROM_ID(TOH.ORGANIZATION_ID) INV_ORG_CODE , TOH.ORGANIZATION_ID, MMT.TRANSACTION_ID TRANSACTION_ID,
TO_CHAR(TOH.CREATION_DATE,'DD-MON-RRRR HH12:MI:SS PM') CREATION_DATE,
TO_CHAR(mmt.transaction_date,'DD-MON-RRRR HH12:MI:SS PM') transaction_date, 
TOH.HEADER_ID WITH_HEADER_ID,
 XX_GET_EMP_NAME_FROM_USER_ID (TOH.CREATED_BY) CREATED_BY,
  TOL.ORGANIZATION_ID,
  TOH.REQUEST_NUMBER,
  TOH.HEADER_ID,
  TOL.LINE_NUMBER,
  TOL.LINE_ID,
  TOL.INVENTORY_ITEM_ID,
  MY_PACKAGE.XXGET_ITEM_DESCRIPTION(TOL.INVENTORY_ITEM_ID) ITEM_DESCRIPTION,
  TOH.DESCRIPTION,
  TOH.MOVE_ORDER_TYPE,
  TOL.LINE_STATUS,
  TOL.QUANTITY,
  TOL.QUANTITY_DELIVERED,
  TOL.QUANTITY_DETAILED
FROM MTL_TXN_REQUEST_HEADERS TOH,
  MTL_TXN_REQUEST_LINES TOL,
  MTL_MATERIAL_TRANSACTIONS MMT
WHERE TOH.HEADER_ID = TOL.HEADER_ID
 AND TOH.ORGANIZATION_ID= TOL.ORGANIZATION_ID
 AND TOL.LINE_ID = MMT.MOVE_ORDER_LINE_ID(+) 
 and  MMT.TRANSACTION_DATE  < (TRUNC(TOH.CREATION_DATE )-30)   
 and TOH.CREATION_DATE between  '01-JAN-2021' and '30-JUN-2021'
 --and MMT.TRANSACTION_ID = 204029
 and TOH.ORGANIZATION_ID IN (
 170,
169,
168,
167,
166,
165,
164,
163,
245
 )
--AND TOH.REQUEST_NUMBER='MO-KSM-0099679'
 --and TOH.HEADER_ID IN (1764072)
-- )


--======================================== TO GET IOT  Creation Date is Greater than Transaction date KSPL  =============================================


SELECT
GET_ORG_CODE_FROM_ID(b.FROM_ORGANIZATION_ID) FROM_INV_ORG_CODE ,
GET_ORG_CODE_FROM_ID(b.TO_ORGANIZATION_ID) TO_INV_ORG_CODE ,
-- a.CREATION_DATE , 
--c.TRANSACTION_DATE 
TO_CHAR(A.CREATION_DATE,'DD-MON-RRRR HH12:MI:SS PM') CREATION_DATE,
TO_CHAR(c.transaction_date,'DD-MON-RRRR HH12:MI:SS PM') transaction_date, 
 XX_GET_EMP_NAME_FROM_USER_ID (a.CREATED_BY) CREATED_BY,
a.SHIPMENT_HEADER_ID,a.ship_to_org_id,a.shipment_num
from RCV_SHIPMENT_HEADERS a, rcv_shipment_lines b, MTL_MATERIAL_TRANSACTIONS c
where a.shipment_header_id= b.shipment_header_id
and a.ship_to_org_id =  b.TO_ORGANIZATION_ID
and b.TO_ORGANIZATION_ID   = c.TRANSFER_ORGANIZATION_ID
and a.shipment_num = c.SHIPMENT_NUMBER
and a.ORGANIZATION_ID = c.ORGANIZATION_ID
and b.MMT_TRANSACTION_ID = c.TRANSACTION_ID
 and  C.TRANSACTION_DATE  < (TRUNC(A.CREATION_DATE )-30)   
 and A.CREATION_DATE between  '01-JAN-2021' and '30-JUN-2021'
--and  B.FROM_ORGANIZATION_ID IN (121,150,149,148,147,146,145,144,143,142,141 )


--======================================== TO GET IOT  Creation Date is Greater than Transaction date  KBIL =============================================
SELECT
GET_ORG_CODE_FROM_ID(b.FROM_ORGANIZATION_ID) FROM_INV_ORG_CODE ,
GET_ORG_CODE_FROM_ID(b.TO_ORGANIZATION_ID) TO_INV_ORG_CODE ,
-- a.CREATION_DATE , 
--c.TRANSACTION_DATE 
TO_CHAR(A.CREATION_DATE,'DD-MON-RRRR HH12:MI:SS PM') CREATION_DATE,
TO_CHAR(c.transaction_date,'DD-MON-RRRR HH12:MI:SS PM') transaction_date, 
 XX_GET_EMP_NAME_FROM_USER_ID (a.CREATED_BY) CREATED_BY,
a.SHIPMENT_HEADER_ID,a.ship_to_org_id,a.shipment_num
from RCV_SHIPMENT_HEADERS a, rcv_shipment_lines b, MTL_MATERIAL_TRANSACTIONS c
where a.shipment_header_id= b.shipment_header_id
and a.ship_to_org_id =  b.TO_ORGANIZATION_ID
and b.TO_ORGANIZATION_ID   = c.TRANSFER_ORGANIZATION_ID
and a.shipment_num = c.SHIPMENT_NUMBER
and a.ORGANIZATION_ID = c.ORGANIZATION_ID
and b.MMT_TRANSACTION_ID = c.TRANSACTION_ID
 and  C.TRANSACTION_DATE  < (TRUNC(A.CREATION_DATE )-30)   
 and A.CREATION_DATE between  '01-JAN-2021' and '30-JUN-2021'
 and a.CREATED_BY <>  1462
 
 select * from RCV_SHIPMENT_HEADERS WHERE SHIPMENT_NUM= 'INT-KLO-0000756'
 
 
  select * from RCV_SHIPMENT_LINES  WHERE SHIPMENT_HEADER_ID = 1038451
 
 
 select * from RCV_TRANSACTIONS WHERE SHIPMENT_HEADER_ID= 1038451
 
 
and  B.FROM_ORGANIZATION_ID IN ( 170,
169,
168,
167,
166,
165,
164,
163,
245
 )



select * from ORG_ORGANIZATION_DEFINITIONS WHERE OPERATING_UNIT= 104

select * from mtl_material_transactions where TRANSACTION_ID = 9091811





